spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vibe_music?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: 123321
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.163.com
    username: yushuimu77@163.com
    password: LXeNxXesQxTx45X5
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required:
          ssl:
            enable: true
          socketFactory:
            port:
            class: javax.net.ssl.SSLSocketFactory
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mybatis-plus:
    type-aliases-package: cn.edu.seig.pojo
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        table-prefix: tb_

role-path-permissions:
  permissions:
    ROLE_ADMIN: "/admin/"
    ROLE_USER:
      - "/user/"
      - "/playlist/"
      - "/artist/"
      - "/song/"
      - "/favorite/"
      - "/comment/"
      - "/banner/"
      - "/feedback/"

minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
#    bucketName: dsad
    bucket: vibe-music-data

storage:
  local:
    songCoversDir: ../vibe-music-data/songCovers
    artistsDir: ../vibe-music-data/artists
    playlistsDir: ../vibe-music-data/playlists
